# Generated by Django 4.0.2 on 2022-02-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_blog_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_blog',
            name='client',
        ),
        migrations.RemoveField(
            model_name='comment_blog',
            name='user',
        ),
    ]
