# Generated by Django 3.2.10 on 2022-02-28 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_contactmessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='informations',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/Info', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
        ),
        migrations.AddField(
            model_name='informations',
            name='location',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informations',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images/Info', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'bmp'])]),
        ),
    ]
