# Generated by Django 4.0.2 on 2022-02-28 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220228_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/Info', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='informations',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images/Info', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
