# Generated by Django 3.2.10 on 2022-02-28 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_informations_icon_alter_informations_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/Info', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='informations',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images/Info', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])]),
        ),
    ]
