# Generated by Django 4.0.2 on 2022-03-01 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_informations_icon_alter_informations_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/icon', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='informations',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images/logo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'jpg'])]),
        ),
    ]
