# Generated by Django 4.0.2 on 2022-02-23 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220218_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='creator',
            name='image',
            field=models.ImageField(upload_to='images/Admin', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
